
# <font color='blue'>Matemática Para Machine Learning</font>

## Lista de Exercícios  - Capítulo 7

O objetivo desta lista de exercícios é você praticar os principais conceitos estudados neste capítulo, ao mesmo tempo que desenvolve suas habilidades em lógica de programação com a linguagem Python. 

Caso tenha dúvidas, isso é absolutamente normal e faça um trabalho de pesquisa a fim de relembrar o formato das operações matemáticas.

Quando encontrar o formato de uma operação que resolva o exercício proposto, use a linguagem Python para representar esta operação. Em essência, é assim que aplicamos Matemática Para Machine Learning, construindo algoritmos e representando esses algoritmos em linguagem de programação.

Divirta-se!!

### Exercício 1 - Resolva o sistema de equações:

# 1x + 1y = 18
# 2x + 4y = 24

In [1]:
# Solução

import numpy as np
expressao1 = np.array([[1, 1],[2,4]])
expressao2 = np.array([18, 24])

x, y = np.linalg.solve(expressao1, expressao2)
print("Os valores de x e y nas equações acima são, respectivamente:", x, y)

Os valores de x e y nas equações acima são, respectivamente: 24.0 -6.0


### Exercício 2 - Resolva o sistema linear abaixo:

# x+y+z = 2

# 2x-6y-z=-1

# 3x-2z=8

Dica: organize os coeficientes na orientação das linhas no sistema linear.

In [2]:
# Solução 

import numpy as np
a = np.array([[1,1,1],[2,-6,-1],[3,0,-2]])
b = np.array([2,-1,8])

resultado1 = np.linalg.solve(a, b)
print(resultado1)

[ 2.  1. -1.]


### Exercício 3 - Resolva o sistema linear abaixo:

# x+y+z = 2

# 2x-6y-z=-1

# 3x-2z=8

Dica: organize os coeficientes na orientação das colunas no sistema linear.

In [3]:
# Solução 

import numpy as np
a = np.array([[1,2,3],[1,-6,0],[1,-1,-2]])
b = np.array([2,-1,8])

resultado2 = np.linalg.solve(a.T, b)
print(resultado2)

[ 2.  1. -1.]


### Exercício 4 - Resolva o sistema linear abaixo usando o método da matriz inversa:

# x+y+z = 2

# 2x-6y-z=-1

# 3x-2z=8

In [4]:
# Solução 

import numpy as np
a = np.array([[1,2,3],[1,-6,0],[1,-1,-2]])
b = np.array([2,-1,8])

# X = (A-1) . b
resultado3 = np.dot(b, np.linalg.inv(a))
print(resultado3)

[ 2.  1. -1.]


### Exercício 5 - Resolva o sistema linear abaixo:

# 3x+2y-4z+t = 30

# 2x+3y+3z+2t=150

# 5x-3y+z-5t=140

# x+y+z+t=60

In [5]:
# Solução 

A = np.array([[3, 2, -4, 1], [2, 3, 3, 2], [5, -3, 1, -5], [1, 1, 1, 1]])
b = np.array([30, 150, 140, 60])
resultado1 = np.linalg.solve(A, b)
print(resultado1)

[3.00000000e+01 1.00000000e+01 2.00000000e+01 2.77734574e-15]


### Exercício 6 (Desafio) - Desenvolva uma função em Python que obtenha o mesmo resultado da função solve() abaixo.

Dica: sua função deve receber a equação como parâmetro e não as matrizes.

In [6]:
import numpy as np
a = np.array([[3,5],[12,-3]]) 
b = np.array([[29],[24]])
np.linalg.solve(a,b)

array([[3.],
       [4.]])

In [7]:
# Solução 

def mysolve(eq, var=('x', 'y')):
    import re

    var_re = re.compile(r'(\+|\-)\s*(\d*)\s*\*?\s*(x|y)')
    const_re = re.compile(r'(\+|\-)\s*(\-?\d+)$')

    constants, eqns, coeffs, default  = [],[], {'x': [], 'y': []}, {'': '1'}

    for e in eq.split(';'):
        eq1 = e.replace("="," - ").strip()
        if not eq1.startswith('-'):
            eq1 = '+' + eq1
        eqns.append(eq1)

    var_eq1, var_eq2 = map(var_re.findall, eqns)

    constants = [-1*int(x[0][1]) for x in map(const_re.findall, eqns)]
    [coeffs[x[2]].append(int((x[0]+ default.get(x[1], x[1])).strip())) for x in (var_eq1 + var_eq2)]
    
    ycoeff = coeffs['y']
    xcoeff = coeffs['x']

    # Ajuste as equações para receber y e resolva para x
    if ycoeff[0]*ycoeff[1] > 0:
        ycoeff[1] *= -1
        xcoeff[0] *= ycoeff[1]
        constants[0] *= -1*ycoeff[1]        
    else:
        xcoeff[0] *= -1*ycoeff[1]
        constants[0] *= ycoeff[1]
        
    xcoeff[1] *= ycoeff[0]
    constants[1] *= -1*ycoeff[0]

    # Obtém x
    xval = sum(constants)*1.0/sum(xcoeff)

    # Agora resolva para y usando o valor de x
    z = eval(eqns[0],{'x': xval, 'y': 1j})
    yval = -z.real*1.0/z.imag

    return (xval, yval)

In [8]:
# Solução 

mysolve('3*x + 5*y = 29; 12*x - 3*y = 24')

(3.0, 4.0)

## Fim